Task/intentTask
Feinei/AndroidHomeWork pull request #4
Opened 2019-10-21 14:22 UTC by Feinei

2019-10-28 19:24 UTC, NailShaykhrazievItis requested changes

2019-10-28 19:24 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/homework/SendingActivity.kt
> +    private val PICKFILE_RESULT_CODE = 0
private const val - для констант

2019-10-28 19:24 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/activity_getting.xml
> +            android:text=""
сортировка
ctrl(cmd)+alt+L

2019-10-28 21:42 UTC, Feinei commented on app/src/main/res/layout/activity_getting.xml
> +            android:text=""
прожал ctrl(cmd)+alt+L

2019-10-28 21:42 UTC, Feinei commented on app/src/main/res/layout/activity_getting.xml
> +            android:text=""
no lines changed

2019-10-29 07:30 UTC, NailShaykhrazievItis approved these changes

2019-11-01 09:06 UTC, closed without merging