Task/recyclerTask
Feinei/AndroidHomeWork pull request #5
Opened 2019-10-28 21:38 UTC by Feinei

![pullReq](https://user-images.githubusercontent.com/42945205/67720225-6d1d3080-f9e4-11e9-8176-73962f6b4a58.jpg)
![pullReq2](https://user-images.githubusercontent.com/42945205/67720229-6f7f8a80-f9e4-11e9-941e-d09c88857c8f.jpg)

2019-11-09 17:54 UTC, NailShaykhrazievItis requested changes

2019-11-09 17:54 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/homework/AboutActivity.kt
> +        val name = intent?.extras?.getString(KEY_NAME) ?: "Unknown"
"Unknown" вынести в константу типa DEFAULT_STRING or something better

2019-11-09 17:54 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/homework/Friend.kt
> +)
add single line on file end

2019-11-09 17:54 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/homework/FriendAdapter.kt
> +}
add single line on file end

2019-11-09 17:54 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/homework/FriendItemHolder.kt
> +}
add single line on file end

2019-11-09 17:54 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/homework/MainActivity.kt
> +        adapter = FriendAdapter(getDataSource()) { friend ->
friend в принципе излишен
`
FriendAdapter(getDataSource())
{
navigateToAbout(it)
}
`

2019-11-09 17:54 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/homework/MainActivity.kt
> +    private fun navigateToAbout(friend: Friend) {
=

2019-11-09 17:54 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/homework/MainActivity.kt
> +    private fun getDataSource(): List<Friend> = listOf(
Лучше вынести в отдельный класс FriendRepository: 
`object FriendRepository {
getDataSource(): List<Friend> = listOf(...)
}`

2019-11-09 17:54 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/activity_about.xml
> +            android:text="Name:"
ctrl+alt+L
sorting by alphabet

2019-11-10 12:25 UTC, Feinei commented on app/src/main/res/layout/activity_about.xml
> +            android:text="Name:"
и так всё верно же? no lines changed

2019-11-12 11:26 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/activity_about.xml
> +            android:text="Name:"
Нет.
Сначала 
id
style
layout params by alphabet
view parms by  alphabet
app params by  alphabet

2019-11-12 11:26 UTC, NailShaykhrazievItis approved these changes

2019-11-13 13:02 UTC, closed without merging